version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
#        restart: always
        volumes:
            - ".:/app"
        depends_on:
            - "php"
            - "mongodb"
    php:
        build:
            context: ./etc/php
            args:
                TIMEZONE: "Europe/Kiev"
#        restart: always
        volumes:
            - .:/app
    composer:
        image: composer
        volumes:
            - .:/app
    mongodb:
        image: mongo
#        restart: always
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger