version: '2'
services:
    web:
        build:
            context: ./etc/nginx
        image: nginx:latest
        ports:
            - "8000:80"
        restart: always
        volumes:
            - /Users/timur/htdocs/ria-auto:/app
        depends_on:
            - "php"
            - "mongodb"
#        command: /bin/bash -c "cat /etc/nginx/conf.d/ria.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    php:
        build:
            context: ./etc/php
            args:
                TIMEZONE: "Europe/Kiev"
        restart: always
        volumes:
            - /Users/timur/htdocs/ria-auto:/app
    mongodb:
        image: mongo
#        restart: always
        volumes:
            - "./data/db/mongo:/data/db"
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger